# Generated by Django 3.2.5 on 2021-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('display_url', models.FileField(upload_to='category/')),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('date_time_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=8)),
                ('discount', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_image', models.FileField(upload_to='product/')),
                ('vendor_name', models.CharField(max_length=50)),
                ('available_stock', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('tax_percentage', models.FloatField()),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('date_time_updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
