# Generated by Django 3.2.5 on 2021-08-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210814_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
