# Generated by Django 3.2.5 on 2021-08-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
    ]
