# Generated by Django 3.2.5 on 2021-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_addedby_subdealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
