# Generated by Django 3.2.5 on 2021-08-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_auth_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_subdeler',
            new_name='is_subdealer',
        ),
    ]
