# Generated by Django 3.2.5 on 2021-08-15 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_subdeler_customuser_is_subdealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdealer',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subdealer'),
        ),
    ]
