# Generated by Django 3.2.5 on 2021-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210925_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
