# Generated by Django 3.2.5 on 2021-09-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210926_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ref_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.channelpartner'),
        ),
    ]
