# Generated by Django 3.2.5 on 2021-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210815_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pin_code',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_address',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
