# Generated by Django 3.2.5 on 2021-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210815_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
