# Generated by Django 3.2.5 on 2021-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20210815_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
