# Generated by Django 3.2.5 on 2021-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20210909_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
