# Generated by Django 3.2.5 on 2021-09-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20210909_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierdelivery',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='courier_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.courierdelivery'),
        ),
    ]
