# Generated by Django 3.2.5 on 2021-09-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_courierdelivery_ref_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierdelivery',
            old_name='ref_phone',
            new_name='courier_ref_phone',
        ),
    ]
