# Generated by Django 3.2.5 on 2021-09-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_rename_ref_phone_courierdelivery_courier_ref_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courier_details',
        ),
        migrations.RemoveField(
            model_name='courierdelivery',
            name='courier_ref_phone',
        ),
        migrations.AddField(
            model_name='courierdelivery',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart'),
        ),
    ]
